import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import ts from 'typescript'

const source = await readFile(new URL('../src/duelEngine.ts', import.meta.url), 'utf8')
const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020 } })
const { createQuestion, initialPace, learnPace, predictPace, scoreAnswer, modes, ROUND_COUNT } = await import(`data:text/javascript;base64,${Buffer.from(outputText).toString('base64')}`)
let seed = 84219
const random = () => { seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0; return seed / 2 ** 32 }
let questions = 0
for (const { id } of modes) {
  for (const rng of [random, () => 0, () => .999999]) {
    for (let sample = 0; sample < 100; sample++) {
      const question = createQuestion(sample % ROUND_COUNT + 1, id, rng)
      assert.equal(new Set(question.choices).size, 4)
      assert.equal(question.choices.filter(value => value === question.answer).length, 1)
      assert(question.choices.every(Number.isInteger))
      assert.match(question.text, /^[\d\s()+×÷−]+$/)
      // Evaluate only arithmetic generated by this module, after validating its alphabet.
      const expression = question.text.replaceAll('×', '*').replaceAll('÷', '/').replaceAll('−', '-')
      assert.equal(Function(`"use strict"; return (${expression})`)(), question.answer)
      questions++
    }
  }
}
let model = initialPace()
const originalPrediction = predictPace(model, 1, 'sprint')
for (let i = 0; i < 20; i++) model = learnPace(model, 1, 2700)
assert.equal(model.samples, 20)
assert(predictPace(model, 1, 'sprint') < originalPrediction)
assert(Math.abs(predictPace(model, 1, 'sprint') - 2700) < 50)
for (const duration of [1, 1000000]) {
  let extreme = initialPace()
  for (let i = 0; i < 100; i++) extreme = learnPace(extreme, 4, duration)
  for (const { id } of modes) {
    const prediction = predictPace(extreme, 4, id)
    assert(prediction >= 2300 && prediction <= 7200)
  }
}
assert(scoreAnswer('sprint', 900, 3600, 1) > scoreAnswer('sprint', 2700, 3600, 1))
assert(scoreAnswer('sprint', 900, 3600, 3) > scoreAnswer('sprint', 900, 3600, 1))
assert(scoreAnswer('expert', 900, 3600, 1) > scoreAnswer('sprint', 900, 3600, 1))
assert.equal(scoreAnswer('practice', 900, 3600, 1), scoreAnswer('practice', 100000, 3600, 1))
assert.equal(scoreAnswer('sprint', 3600, 3600, 1), 100)
console.log(`Passed: ${questions} generated questions, adaptive pace convergence/bounds, and speed/streak/mode scoring.`)
